### ISSUE TITLE
AttributeError: Session instance has no attribute 'get_installpkg_path'

### ISSUE THREAD

**Issue by ahvigil** [tox-dev/detox#15]
`get_installpkg_path` was removed from the tox Session object as of 3.3.0, at least according to the documentation:
https://tox.readthedocs.io/en/3.3.0/plugins.html#tox.session.Session

This results in tests failing to run, although the end result is reported as a success.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 460, in fire_timers
    timer()
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/eventlet/greenthread.py", line 219, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/detox/proc.py", line 169, in _dispatchprovider
    self._resources[spec] = res = provider(*parts)
  File "/usr/local/lib/python2.7/site-packages/detox/proc.py", line 116, in provide_sdist
    sdistpath = self.toxsession.get_installpkg_path()
AttributeError: Session instance has no attribute 'get_installpkg_path'
py2 installdeps: mock, pytest, pytest-cov, pytest-html, Cython
Post stage
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 88, in _spawn_n_impl
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/detox/proc.py", line 140, in runtests
    venv, sdist = self.getresources("venv:%s" % venvname, "sdist")
  File "/usr/local/lib/python2.7/site-packages/detox/proc.py", line 156, in getresources
    return self._resources.getresources(*specs)
  File "/usr/local/lib/python2.7/site-packages/detox/proc.py", line 181, in getresources
    self._spec2thread[spec].wait()
  File "/usr/local/lib/python2.7/site-packages/eventlet/greenthread.py", line 180, in wait
    return self._exit_event.wait()
  File "/usr/local/lib/python2.7/site-packages/eventlet/event.py", line 132, in wait
    current.throw(*self._exc)
  File "/usr/local/lib/python2.7/site-packages/eventlet/greenthread.py", line 219, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/detox/proc.py", line 169, in _dispatchprovider
    self._resources[spec] = res = provider(*parts)
  File "/usr/local/lib/python2.7/site-packages/detox/proc.py", line 116, in provide_sdist
    sdistpath = self.toxsession.get_installpkg_path()
AttributeError: Session instance has no attribute 'get_installpkg_path'
___________________________________ summary ____________________________________
  py2: commands succeeded
  congratulations :)
```

I'm not sure how much work it would be to remove the use of `Session.get_installpkg_path` here. As a workaround, you could pin the required version of tox to <3.3

**$ pip freeze**
detox==0.13
dnspython==1.15.0
enum34==1.1.6
eventlet==0.24.1
greenlet==0.4.15
monotonic==1.5
pluggy==0.7.1
py==1.6.0
six==1.11.0
toml==0.9.6
tox==3.3.0
virtualenv==16.0.0

**$ python --version**
Python 2.7.15

**Comment by rpkilby** [comment]
Just found this out as well. Example:
- https://github.com/carltongibson/django-filter/pull/977
- https://travis-ci.org/carltongibson/django-filter/jobs/431241166

**Comment by obestwalter** [comment]
Hi @ahvigil, thanks for reporting. If the tests of detox would have been run in the last few months this breakage would have been obvious. It becomes clear from this that development and maintenance for detox has stopped as none of the organization is using detox themselves. I opened an issuse and updated the README making that clear.

There is in issue over at [tox](https://github.com/tox-dev/tox/issues/439) that will likely be the one coordinating if and how parallel execution orchestrated by tox has a future @gaborbernat already expressed interest, so there is hope :)

**Comment by obestwalter** [comment]
fixed with https://github.com/tox-dev/detox/commit/c1a117343428353f6156219066b7ba9257753dff on master.
