### ISSUE TITLE
Path issues in 0.15

### ISSUE THREAD

**Issue by iScrE4m** [tox-dev/detox#33]
detox==0.15, tox==3.5.2 

```
Traceback (most recent call last):\         
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/py/_path/local.py", line 152, in __init__
    path = fspath(path)
TypeError: expected str, bytes or os.PathLike object, not tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 460, in fire_timers
    timer()
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/eventlet/event.py", line 175, in _do_send
    waiter.switch(result)
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/eventlet/greenthread.py", line 219, in main
    result = function(*args, **kwargs)
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/detox/proc.py", line 151, in runtests
    if self.toxsession.installpkg(venv, sdist):
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/tox/session.py", line 551, in installpkg
    self.resultlog.set_header(installpkg=py.path.local(path))
  File "/Users/david.jetelina/.local/share/virtualenvs/kzlib-lvViDtZ5/lib/python3.7/site-packages/py/_path/local.py", line 154, in __init__
    raise ValueError("can only pass None, Path instances "
ValueError: can only pass None, Path instances or non-empty strings to LocalPath
```

Tried rolling back to 0.13, which is incompatible with tox 3.5.2, so I froze my project at tox 3.2.1 and detox 0.13 for now (works perfectly).

**Comment by obestwalter** [comment]
Hi @iScrE4m, thanks for reporting this. This is anincompatibility introduced by changes in tox (starting here: https://travis-ci.org/tox-dev/detox/builds/437378523). I will see if I can fix it over the weekend and cut another release.
